apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: demo-rdma-3
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running 
  mpiReplicaSpecs:
    Launcher:
      restartPolicy: OnFailure
      replicas: 1
      template:
        metadata:
          labels:
            mount-eos: "true" 
            mount-cvmfs: "true" 
            mount-afs: "true" 
            home: "eos"
        spec:
          containers:
          - image: registry.cern.ch/ngt/lxplus-like:9
            name: launcher
            command: ["/usr/bin/tini", "--", "sleep", "infinity"]
            resources:
              limits:
                nvidia.com/mig-3g.47gb: 1 
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-H100-NVL
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            mount-eos: "true" 
            mount-cvmfs: "true" 
            mount-afs: "true" 
            home: "eos" 
        spec:
          containers:
          - image: registry.cern.ch/ngt/lxplus-like:9
            name: worker
            resources:
              limits:
                nvidia.com/mig-3g.47gb: 1 
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-H100-NVL
