apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: demo-rdma-sxm
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running 
  mpiReplicaSpecs:
    Launcher:
      restartPolicy: OnFailure
      replicas: 1
      template:
        metadata:
          labels:
            mount-eos: "true" 
            mount-cvmfs: "true" 
            mount-afs: "true" 
            home: "eos"
        spec:
          containers:
          - image: registry.cern.ch/ngt/lxplus-like:cuda-aware-mpi
            name: launcher
            command: ["/usr/bin/tini", "--", "sleep", "infinity"]
            securityContext:
              runAsUser: 0
            resources:
              limits:
                nvidia.com/gpu: 1 
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            mount-eos: "true" 
            mount-cvmfs: "true" 
            mount-afs: "true" 
            home: "eos" 
        spec:
          containers:
          - image: registry.cern.ch/ngt/lxplus-like:cuda-aware-mpi
            name: worker
            securityContext:
              runAsUser: 0
            resources:
              limits:
                nvidia.com/gpu: 1 
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
