apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: benchmark
spec:
  slotsPerWorker: 4
  runPolicy:
    cleanPodPolicy: Running 
  mpiReplicaSpecs:
    Launcher:
      restartPolicy: OnFailure
      replicas: 1
      template:
        metadata:
          labels:
            mount-eos: "true" 
            mount-cvmfs: "true" 
            mount-afs: "true" 
            home: "eos"
        spec:
          containers:
          - image: registry.cern.ch/hhansen/e2e-lxplus
            name: launcher
            command: ["sleep", "infinity"]
    Worker:
      replicas: 1
      template:
        metadata:
          labels:
            mount-eos: "true" 
            mount-cvmfs: "true" 
            mount-afs: "true" 
            home: "eos" 
        spec:
          containers:
          - image: registry.cern.ch/hhansen/e2e-lxplus
            name: worker
            resources:
              limits:
                nvidia.com/gpu: 1 
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
